server:
  port: 5001

spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    username: root
    password:
    url: jdbc:mysql://coinnotice.cnehhajyqjc9.ap-northeast-2.rds.amazonaws.com:3306/coin_notice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver