server:
  port: 5000
spring:
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/coin_notice?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
